apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: quarkssecrets.quarks.cloudfoundry.org
spec:
  conversion:
    strategy: None
  group: quarks.cloudfoundry.org
  names:
    kind: QuarksSecret
    listKind: QuarksSecretList
    plural: quarkssecrets
    shortNames:
    - qsec
    - qsecs
    singular: quarkssecret
  preserveUnknownFields: false
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            request:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            secretName:
              description: The name of the generated secret
              minLength: 1
              type: string
            type:
              description: 'What kind of secret to generate: password, certificate,
                ssh, rsa'
              minLength: 1
              type: string
          required:
          - secretName
          - type
          type: object
        status:
          properties:
            generated:
              type: boolean
            lastReconcile:
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
